// Canonical book table for Peractum.
// `dataset` matches the book `name` field in the scrollmapper VulgClementine/CPDV JSON.
// Latin titles follow Clementine Vulgate usage (Regum I–IV for Samuel/Kings,
// Paralipomenon for Chronicles, Ecclesiasticus for Sirach, etc.).
// group: "vetus" | "novum"

export const BOOKS = [
  { dataset: "Genesis", slug: "genesis", latin: "Genesis", english: "Genesis", group: "vetus" },
  { dataset: "Exodus", slug: "exodus", latin: "Exodus", english: "Exodus", group: "vetus" },
  { dataset: "Leviticus", slug: "leviticus", latin: "Leviticus", english: "Leviticus", group: "vetus" },
  { dataset: "Numbers", slug: "numeri", latin: "Numeri", english: "Numbers", group: "vetus" },
  { dataset: "Deuteronomy", slug: "deuteronomium", latin: "Deuteronomium", english: "Deuteronomy", group: "vetus" },
  { dataset: "Joshua", slug: "josue", latin: "Josue", english: "Joshua", group: "vetus" },
  { dataset: "Judges", slug: "judicum", latin: "Judicum", english: "Judges", group: "vetus" },
  { dataset: "Ruth", slug: "ruth", latin: "Ruth", english: "Ruth", group: "vetus" },
  { dataset: "I Samuel", slug: "regum-1", latin: "Regum I", english: "1 Samuel", group: "vetus" },
  { dataset: "II Samuel", slug: "regum-2", latin: "Regum II", english: "2 Samuel", group: "vetus" },
  { dataset: "I Kings", slug: "regum-3", latin: "Regum III", english: "1 Kings", group: "vetus" },
  { dataset: "II Kings", slug: "regum-4", latin: "Regum IV", english: "2 Kings", group: "vetus" },
  { dataset: "I Chronicles", slug: "paralipomenon-1", latin: "Paralipomenon I", english: "1 Chronicles", group: "vetus" },
  { dataset: "II Chronicles", slug: "paralipomenon-2", latin: "Paralipomenon II", english: "2 Chronicles", group: "vetus" },
  { dataset: "Ezra", slug: "esdrae", latin: "Esdræ", english: "Ezra", group: "vetus" },
  { dataset: "Nehemiah", slug: "nehemiae", latin: "Nehemiæ", english: "Nehemiah", group: "vetus" },
  { dataset: "Tobit", slug: "tobiae", latin: "Tobiæ", english: "Tobit", group: "vetus" },
  { dataset: "Judith", slug: "judith", latin: "Judith", english: "Judith", group: "vetus" },
  { dataset: "Esther", slug: "esther", latin: "Esther", english: "Esther", group: "vetus" },
  { dataset: "Job", slug: "job", latin: "Job", english: "Job", group: "vetus" },
  { dataset: "Psalms", slug: "psalmi", latin: "Psalmi", english: "Psalms", group: "vetus" },
  { dataset: "Proverbs", slug: "proverbia", latin: "Proverbia", english: "Proverbs", group: "vetus" },
  { dataset: "Ecclesiastes", slug: "ecclesiastes", latin: "Ecclesiastes", english: "Ecclesiastes", group: "vetus" },
  { dataset: "Song of Solomon", slug: "canticum-canticorum", latin: "Canticum Canticorum", english: "Song of Songs", group: "vetus" },
  { dataset: "Wisdom", slug: "sapientia", latin: "Sapientia", english: "Wisdom", group: "vetus" },
  { dataset: "Sirach", slug: "ecclesiasticus", latin: "Ecclesiasticus", english: "Sirach", group: "vetus" },
  { dataset: "Isaiah", slug: "isaias", latin: "Isaias", english: "Isaiah", group: "vetus" },
  { dataset: "Jeremiah", slug: "jeremias", latin: "Jeremias", english: "Jeremiah", group: "vetus" },
  { dataset: "Lamentations", slug: "lamentationes", latin: "Lamentationes", english: "Lamentations", group: "vetus" },
  { dataset: "Baruch", slug: "baruch", latin: "Baruch", english: "Baruch", group: "vetus" },
  { dataset: "Ezekiel", slug: "ezechiel", latin: "Ezechiel", english: "Ezekiel", group: "vetus" },
  { dataset: "Daniel", slug: "daniel", latin: "Daniel", english: "Daniel", group: "vetus" },
  { dataset: "Hosea", slug: "osee", latin: "Osee", english: "Hosea", group: "vetus" },
  { dataset: "Joel", slug: "joel", latin: "Joel", english: "Joel", group: "vetus" },
  { dataset: "Amos", slug: "amos", latin: "Amos", english: "Amos", group: "vetus" },
  { dataset: "Obadiah", slug: "abdias", latin: "Abdias", english: "Obadiah", group: "vetus" },
  { dataset: "Jonah", slug: "jonas", latin: "Jonas", english: "Jonah", group: "vetus" },
  { dataset: "Micah", slug: "michaeas", latin: "Michæas", english: "Micah", group: "vetus" },
  { dataset: "Nahum", slug: "nahum", latin: "Nahum", english: "Nahum", group: "vetus" },
  { dataset: "Habakkuk", slug: "habacuc", latin: "Habacuc", english: "Habakkuk", group: "vetus" },
  { dataset: "Zephaniah", slug: "sophonias", latin: "Sophonias", english: "Zephaniah", group: "vetus" },
  { dataset: "Haggai", slug: "aggaeus", latin: "Aggæus", english: "Haggai", group: "vetus" },
  { dataset: "Zechariah", slug: "zacharias", latin: "Zacharias", english: "Zechariah", group: "vetus" },
  { dataset: "Malachi", slug: "malachias", latin: "Malachias", english: "Malachi", group: "vetus" },
  { dataset: "I Maccabees", slug: "machabaeorum-1", latin: "Machabæorum I", english: "1 Maccabees", group: "vetus" },
  { dataset: "II Maccabees", slug: "machabaeorum-2", latin: "Machabæorum II", english: "2 Maccabees", group: "vetus" },
  { dataset: "Matthew", slug: "matthaeus", latin: "Matthæus", english: "Matthew", group: "novum" },
  { dataset: "Mark", slug: "marcus", latin: "Marcus", english: "Mark", group: "novum" },
  { dataset: "Luke", slug: "lucas", latin: "Lucas", english: "Luke", group: "novum" },
  { dataset: "John", slug: "joannes", latin: "Joannes", english: "John", group: "novum" },
  { dataset: "Acts", slug: "actus", latin: "Actus Apostolorum", english: "Acts", group: "novum" },
  { dataset: "Romans", slug: "ad-romanos", latin: "Ad Romanos", english: "Romans", group: "novum" },
  { dataset: "I Corinthians", slug: "ad-corinthios-1", latin: "Ad Corinthios I", english: "1 Corinthians", group: "novum" },
  { dataset: "II Corinthians", slug: "ad-corinthios-2", latin: "Ad Corinthios II", english: "2 Corinthians", group: "novum" },
  { dataset: "Galatians", slug: "ad-galatas", latin: "Ad Galatas", english: "Galatians", group: "novum" },
  { dataset: "Ephesians", slug: "ad-ephesios", latin: "Ad Ephesios", english: "Ephesians", group: "novum" },
  { dataset: "Philippians", slug: "ad-philippenses", latin: "Ad Philippenses", english: "Philippians", group: "novum" },
  { dataset: "Colossians", slug: "ad-colossenses", latin: "Ad Colossenses", english: "Colossians", group: "novum" },
  { dataset: "I Thessalonians", slug: "ad-thessalonicenses-1", latin: "Ad Thessalonicenses I", english: "1 Thessalonians", group: "novum" },
  { dataset: "II Thessalonians", slug: "ad-thessalonicenses-2", latin: "Ad Thessalonicenses II", english: "2 Thessalonians", group: "novum" },
  { dataset: "I Timothy", slug: "ad-timotheum-1", latin: "Ad Timotheum I", english: "1 Timothy", group: "novum" },
  { dataset: "II Timothy", slug: "ad-timotheum-2", latin: "Ad Timotheum II", english: "2 Timothy", group: "novum" },
  { dataset: "Titus", slug: "ad-titum", latin: "Ad Titum", english: "Titus", group: "novum" },
  { dataset: "Philemon", slug: "ad-philemonem", latin: "Ad Philemonem", english: "Philemon", group: "novum" },
  { dataset: "Hebrews", slug: "ad-hebraeos", latin: "Ad Hebræos", english: "Hebrews", group: "novum" },
  { dataset: "James", slug: "jacobi", latin: "Jacobi", english: "James", group: "novum" },
  { dataset: "I Peter", slug: "petri-1", latin: "Petri I", english: "1 Peter", group: "novum" },
  { dataset: "II Peter", slug: "petri-2", latin: "Petri II", english: "2 Peter", group: "novum" },
  { dataset: "I John", slug: "joannis-1", latin: "Joannis I", english: "1 John", group: "novum" },
  { dataset: "II John", slug: "joannis-2", latin: "Joannis II", english: "2 John", group: "novum" },
  { dataset: "III John", slug: "joannis-3", latin: "Joannis III", english: "3 John", group: "novum" },
  { dataset: "Jude", slug: "judae", latin: "Judæ", english: "Jude", group: "novum" },
  { dataset: "Revelation of John", slug: "apocalypsis", latin: "Apocalypsis", english: "Revelation", group: "novum" },
];
